# WGS-84 latitude for the centre position of shape [1/10 micro degree]
int32 latitude

# WGS-84 longitude for the centre position of shape [1/10 micro degree]
int32 longitude

# Distance a of the geometric shape [metres] (always non-zero)
uint16 distance_a

# Distance b of the geometric shape [metres]
uint16 distance_b

# Angle of the geometric shape [degrees from North]
uint16 angle

# Shape @sa eETSIGeoNetDestType
uint8 shape

# Padding
uint8 unused